# Generated by Django 2.0.6 on 2018-06-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='task_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True, verbose_name='Celery tasks identifier'),
        ),
    ]
