# Generated by Django 3.2 on 2021-04-26 09:43

from django.conf import settings
from django.db import migrations, models
import nuntius.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={"swappable": "NUNTIUS_SEGMENT_MODEL",},
            bases=(nuntius.models.BaseSegment, models.Model),
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                (
                    "subscriber_status",
                    models.IntegerField(
                        choices=[
                            (1, "Subscribed"),
                            (2, "Unsubscribed"),
                            (3, "Bounced"),
                            (4, "Complained"),
                        ]
                    ),
                ),
                ("segments", models.ManyToManyField(to=settings.NUNTIUS_SEGMENT_MODEL)),
            ],
            options={"abstract": False, "swappable": "NUNTIUS_SUBSCRIBER_MODEL",},
            bases=(nuntius.models.AbstractSubscriber, models.Model),
        ),
    ]
