# Generated by Django 2.2.27 on 2022-04-04 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standalone", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="segment",
            options={"verbose_name": "List", "verbose_name_plural": "Lists"},
        ),
        migrations.AlterModelOptions(
            name="subscriber",
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
            },
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="segments",
            field=models.ManyToManyField(
                to=settings.NUNTIUS_SEGMENT_MODEL, verbose_name="Lists"
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="subscriber_status",
            field=models.IntegerField(
                choices=[
                    (1, "Subscribed"),
                    (2, "Unsubscribed"),
                    (3, "Bounced"),
                    (4, "Complained"),
                ],
                verbose_name="Subscriber status",
            ),
        ),
    ]
